services:

  demography-people-v1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/barpav/demography-people:v1
    container_name: demography-people-v1
    environment:
      - DMG_STORAGE_HOST=${DMG_STORAGE}
      - DMG_STORAGE_PORT=${DMG_STORAGE_PORT}
      - DMG_STORAGE_DATABASE=${PG_DB}
      - DMG_STORAGE_USER=${PG_USER}
      - DMG_STORAGE_PASSWORD=${PG_PASSWORD}
      - DMG_STATS_TIMEOUT_MS=${DMG_STATS_TIMEOUT_MS}
      - DMG_HTTP_PORT=${DMG_HTTP_PORT}
    ports:
      - ${DMG_HTTP_PORT}:${DMG_HTTP_PORT}
    depends_on:
      demography-storage:
        condition: service_healthy
      demography-migrations:
        condition: service_completed_successfully

  demography-storage:
    image: postgres:alpine
    container_name: demography-storage
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    expose:
      - ${DMG_STORAGE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 5
  
  demography-migrations:
    image: migrate/migrate:v4.16.2
    container_name: demography-migrations
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-database",
        "postgres://${PG_USER}:${PG_PASSWORD}@${DMG_STORAGE}:${DMG_STORAGE_PORT}/${PG_DB}?sslmode=disable",
        "-path",
        "/migrations",
        "up",
      ]
    depends_on:
      demography-storage:
        condition: service_healthy